<h1 class="page-title">Cadastro de Privilégios</h1>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="<?php echo $this->url('home'); ?>">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="<?php echo $this->url('isconfiguracao-admin/default', array('controller' => 'privilegios', 'action' => 'index')); ?>">Privilégios</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li><span>Novo</span></li>
    </ul>
</div>
<div class="portlet light">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-plus font-yellow"></i>
            <span class="caption-subject font-yellow bold uppercase">Novo</span>
        </div>
    </div>
    <div class="portlet-body form">
        <?php echo $this->form()->openTag($form); ?>
        <div class="form-body">
            <?php echo $this->partial('partials/notificacoes'); ?>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("grupo"));
                        echo $this->formElement($form->get("grupo"));
                        echo $this->formElementErrors($form->get("grupo"), array('class' => "parsley-error-list"));
                        ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("funcionalidade"));
                        echo $this->formElement($form->get("funcionalidade"));
                        echo $this->formElementErrors($form->get("funcionalidade"), array('class' => "parsley-error-list"));
                        ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("ler"));
                        echo $this->formElement($form->get("ler"));
                        echo $this->formElementErrors($form->get("ler"), array('class' => "parsley-error-list"));
                        ?>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("escrever"));
                        echo $this->formElement($form->get("escrever"));
                        echo $this->formElementErrors($form->get("escrever"), array('class' => "parsley-error-list"));
                        ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-actions right">
            <button type="submit" class="btn grey-mint pull-right" ><i class="fa fa-save"></i> Salvar</button>
            <?php
            echo $this->formElement($form->get("id"));
            echo $this->formElement($form->get("security"));
            ?>
        </div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>