<?php $totalItens = $dados->getTotalItemCount(); ?>
<h1 class="page-title">Cadastro de Grupos</h1>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="<?php echo $this->url('home'); ?>">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>Grupos</span>
        </li>
    </ul>
</div>
<div class="portlet light">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-list font-yellow"></i>
            <span class="caption-subject font-yellow bold uppercase">Exibir/Buscar</span>
            <span class="caption-helper"><?php echo ISBase\Util\IdealizeUtil::itensLocalizados($totalItens, "grupo"); ?></span>
        </div>
    </div>
    <div class="portlet-body form">
        <?php echo $this->form()->openTag($form); ?>
        <div class="form-body">
            <?php echo $this->partial('partials/notificacoes'); ?>
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("status"));
                        echo $this->formElement($form->get("status"));
                        echo $this->formElementErrors($form->get("status"), array('class' => "parsley-error-list"));
                        ?>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("nome"));
                        echo $this->formElement($form->get("nome"));
                        echo $this->formElementErrors($form->get("nome"), array('class' => "parsley-error-list"));
                        ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <button type="submit" class="btn default pull-right"><i class="fa fa-search"></i> Buscar</button>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
    <div class="portlet-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Herança</th>
                        <th class='text-center' width="10">Administrador</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($dados as $grupo) { ?>
                        <tr>
                            <td><?php echo $grupo->getNome(); ?></td>
                            <td width="250"><?php echo!empty($grupo->getHerda()) ? $grupo->getHerda()->getNome() : ""; ?></td>
                            <td class='text-center'><?php echo $grupo->getAdministrador() ? "<span class='label label-sm label-danger'>Sim</span>" : "<span class='label label-sm label-info'>Não</span>"; ?></td>
                        </tr>
                    <?php } if ($totalItens == 0) { ?>
                        <tr>
                            <td colspan="12">Nenhum registro localizado</td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php if ($totalItens > 20) { ?>
            <div class="row">
                <div class="col-md-12 col-sm-12" >
                    <?php echo $this->paginationControl($dados, 'Sliding', 'partials/paginacao', array("filters" => $filtros)); ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>