<?php $totalItens = $dados->getTotalItemCount(); ?>
<h1 class="page-title">Cadastro de Unidades</h1>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="<?php echo $this->url('home'); ?>">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>Unidades</span>
        </li>
    </ul>
</div>
<div class="portlet light ">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-list font-yellow"></i>
            <span class="caption-subject font-yellow bold uppercase">Exibir/Buscar</span>
            <span class="caption-helper"><?php echo ISBase\Util\IdealizeUtil::itensLocalizados($totalItens, "unidade"); ?></span>
        </div>
        <div class="actions">
            <a class="btn grey-mint pull-right" href="<?php echo $this->url('isconfiguracao-admin/default', array('controller' => 'unidades', 'action' => 'novo')); ?>">
                <i class="icon-plus"></i> Nova
            </a>
        </div>
    </div>
    <div class="portlet-body form">
        <?php echo $this->form()->openTag($form); ?>
        <div class="form-body">
            <?php echo $this->partial('partials/notificacoes'); ?>
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("status"));
                        echo $this->formElement($form->get("status"));
                        ?>
                    </div>
                </div>
                <div class="col-md-10">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("filtro"));
                        echo $this->formElement($form->get("filtro"));
                        ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <button type="submit" class="btn grey-salt pull-right"><i class="fa fa-search"></i> Buscar</button>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
    <div class="portlet-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>E-mail</th>
                        <th width="170">Telefone</th>
                        <th class="text-center" width="100">Acessos</th>
                        <th class="text-center" width="100">Últ. Acesso</th>
                        <th class="text-center" width="20">Status</th>
                        <?php if ($acl['escrever']) { ?>
                            <th width="10"></th>
                            <th width="10"></th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($dados as $unidade) { ?>
                        <tr>
                            <td>
                                <?php if ($acl['escrever']) { ?>
                                    <a href="<?php echo $this->url('isconfiguracao-admin/default', array('controller' => 'unidades', 'action' => 'editar', 'id' => $unidade['id'])); ?>">
                                        <?php echo $unidade['nome']; ?>
                                    </a>
                                <?php } else { ?>
                                    <span><?php echo $unidade['nome']; ?></span>
                                <?php } ?>
                            </td>
                            <td><?php echo $unidade['email']; ?></td>
                            <td><?php echo $unidade['telefone']; ?></td>
                            <td class="text-center" id="linha_totalacessos_<?php echo $unidade['id']; ?>">
                                <?php if ($unidade['totalAcessos'] <= 1) { ?>
                                    <span><?php echo $unidade['totalAcessos']; ?></span>
                                <?php } else { ?>
                                    <a href="javascript:;" onclick="unidadesHistoricoAcessos(<?php echo $unidade['id']; ?>, 'linha_totalacessos');" title="Ver histórico de acessos">
                                        <?php echo $unidade['totalAcessos']; ?>
                                    </a>
                                    <img class="display-none" src="/layout/img/loading-spinner-blue.gif" />
                                <?php } ?>
                            </td>
                            <td class="text-center" id="linha_ultimoacesso_<?php echo $unidade['id']; ?>">
                                <?php if ($unidade['totalAcessos'] <= 1) { ?>
                                <span><?php echo ISBase\Util\DataHora::date_string($unidade['ultimoAcesso']); ?></span>
                                <?php } else { ?>
                                    <a href="javascript:;" onclick="unidadesHistoricoAcessos(<?php echo $unidade['id']; ?>, 'linha_ultimoacesso');" title="Ver histórico de acessos">
                                        <?php echo ISBase\Util\DataHora::date_string($unidade['ultimoAcesso']); ?>
                                    </a>
                                    <img class="display-none" src="/layout/img/loading-spinner-blue.gif" />
                                <?php } ?>                           
                            </td>
                            <td class="text-center"><?php echo $unidade['status'] ? "<span class='label label-sm label-info'>Ativo</span>" : "<span class='label label-sm label-danger'>Inativo</span>"; ?></td>
                            <?php if ($acl['escrever']) { ?>
                                <td>
                                    <a class="btn default btn-xs yellow-stripe" href="<?php echo $this->url('isconfiguracao-admin/default', array('controller' => 'unidades', 'action' => 'editar', 'id' => $unidade['id'])); ?>">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                </td>
                                <td>
                                    <?php if ($unidade['status']) { ?>
                                        <a class="btn default btn-xs red-stripe" href="javascript:;" onclick="modal_remover('<?php echo $this->url('isconfiguracao-admin/default', array('controller' => 'unidades', 'action' => 'ativarRemover', 'id' => $unidade['id'])); ?>');"> <i class="fa fa-remove"></i></a>    
                                    <?php } else { ?>
                                        <a class="btn default btn-xs green-stripe" href="<?php echo $this->url('isconfiguracao-admin/default', array('controller' => 'unidades', 'action' => 'ativarRemover', 'id' => $unidade['id'])); ?>"> <i class="fa fa-check"></i></a>    
                                    <?php } ?>
                                </td>
                            <?php } ?>
                        </tr>
                    <?php } if ($totalItens == 0) { ?>
                        <tr>
                            <td colspan="12">Nenhum registro localizado</td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php if ($totalItens > 20) { ?>
            <div class="row">
                <div class="col-md-12 col-sm-12" >
                    <?php echo $this->paginationControl($dados, 'Sliding', 'partials/paginacao', array("filters" => $filtros)); ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>
<div id="modal_remover_item" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">ATENÇÃO</h4>
            </div>
            <div class="modal-body">
                <div class="scroller" style="height:50px" data-always-visible="1" data-rail-visible1="1">
                    <h4>Deseja realmente remover?</h4>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn default" data-dismiss="modal" type="button"><i class="fa fa-remove"></i> Não</button>
                <a class="btn red-haze" id="modal_remover_botao" href="javascript:;"><i class="fa fa-check"></i> Sim</a>
            </div>
        </div>
    </div>
</div>
<div id="modal_acessos" class="modal fade" id="large" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">HISTÓRICO DOS 500 ÚLTIMOS ACESSOS</h4>
            </div>
            <div class="modal-body">
                <div id="conteudo" class="scroller" style="height:400px" data-always-visible="1" data-rail-visible1="1">

                </div>
            </div>
            <div class="modal-footer">
                <button class="btn default" data-dismiss="modal" type="button"><i class="fa fa-remove"></i> Fechar</button>
            </div>
        </div>
    </div>
</div>