<?php $totalItens = $dados->getTotalItemCount(); ?>
<h1 class="page-title">Cadastro de Usuários</h1>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="<?php echo $this->url('home'); ?>">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>Usuários</span>
        </li>
    </ul>
</div>
<div class="portlet light">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-list font-yellow"></i>
            <span class="caption-subject font-yellow bold uppercase">Exibir/Buscar</span>
            <span class="caption-helper"><?php echo ISBase\Util\IdealizeUtil::itensLocalizados($totalItens, "usuario"); ?></span>
        </div>
        <div class="actions">
            <a class="btn grey-mint pull-right" href="<?php echo $this->url('isconfiguracao-admin/default', array(
                'controller' => 'usuarios',
                'action' => 'novo'
            )); ?>">
                <i class="icon-plus"></i> Novo
            </a>
        </div>
    </div>
    <div class="portlet-body form">
        <?php echo $this->form()->openTag($form); ?>
        <div class="form-body">
            <?php echo $this->partial('partials/notificacoes'); ?>
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("status"));
                        echo $this->formElement($form->get("status"));
                        echo $this->formElementErrors($form->get("status"), array('class' => "parsley-error-list"));
                        ?>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("grupo"));
                        echo $this->formElement($form->get("grupo"));
                        echo $this->formElementErrors($form->get("grupo"), array('class' => "parsley-error-list"));
                        ?>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("unidade"));
                        echo $this->formElement($form->get("unidade"));
                        echo $this->formElementErrors($form->get("unidade"), array('class' => "parsley-error-list"));
                        ?>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("filtro"));
                        echo $this->formElement($form->get("filtro"));
                        echo $this->formElementErrors($form->get("filtro"), array('class' => "parsley-error-list"));
                        ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <button type="submit" class="btn default pull-right"><i class="fa fa-search"></i> Buscar</button>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
    <div class="portlet-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th width="10"></th>
                        <th>Nome</th>
                        <th>E-mail</th>
                        <th>Grupo</th>
                        <th>Unidade</th>
                        <th class="text-center" width="100">Tot. Acessos</th>
                        <th width="20">Status</th>
                        <?php if ($acl['escrever']) { ?>
                            <?php if ($administrador) { ?>
                                <th width="20"></th>
                            <?php } ?>
                            <th width="20"></th>
                            <th width="20"></th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($dados as $usuario) { ?>
                        <tr>
                            <td class='text-center'>
                                <img style="width: 35px;" class="img-circle" src="/layout/img/avatar/<?php echo $usuario['sexo'] == "M"
                                    ? "padrao_masc.jpg"
                                    : "padrao_femi.jpg"; ?>" alt="<?php echo $usuario['nome']; ?>">
                            </td>
                            <td>
                                <?php if ($acl['escrever']) { ?>
                                    <a href="<?php echo $this->url('isconfiguracao-admin/default', array(
                                        'controller' => 'usuarios',
                                        'action' => 'editar',
                                        'id' => $usuario['id']
                                    )); ?>">
                                        <?php echo $usuario['nome']; ?>
                                    </a>
                                    <?php } else {echo $usuario['nome'];} ?>
                            </td>
                            <td><?php echo $usuario['email']; ?></td>
                            <td><?php echo $usuario['grupoNome']; ?></td>
                            <td><?php echo $usuario['unidade']; ?></td>
                            <td class="text-center" id="linha_totalacessos_<?php echo $usuario['id']; ?>">
                                <?php if ($usuario['totalAcessos'] <= 1) { ?>
                                    <span><?php echo $usuario['totalAcessos']; ?></span>
                                <?php } else { ?>
                                    <a href="javascript:;" onclick="usuariosHistoricoAcessos(<?php echo $usuario[
                                        'id'
                                    ]; ?>, 'linha_totalacessos');" title="Ver histórico de acessos"><?php echo $usuario['totalAcessos']; ?></a>
                                    <img class="display-none" src="/layout/img/loading-spinner-blue.gif" />
                                <?php } ?>
                            </td>
                            <td><?php echo $usuario['status']
                                ? "<span class='label label-sm label-info'>Ativo</span>"
                                : "<span class='label label-sm label-danger'>Inativo</span>"; ?></td>
                            <?php if ($acl['escrever']) { ?>
                                <?php if ($administrador) { ?>
                                    <td>
                                        <a class="btn default btn-xs purple-stripe" title="Autenticar como <?php echo $usuario[
                                            'nome'
                                        ]; ?>" href="<?php echo $this->url('isconfiguracao-admin/default', array(
    'controller' => 'usuarios',
    'action' => 'autenticarComo',
    'id' => $usuario['id']
)); ?>">
                                            <i class="fa fa-lock"></i>
                                        </a>
                                    </td>
                                <?php } ?>
                                <td>
                                    <a class="btn default btn-xs yellow-stripe" href="<?php echo $this->url('isconfiguracao-admin/default', array(
                                        'controller' => 'usuarios',
                                        'action' => 'editar',
                                        'id' => $usuario['id']
                                    )); ?>">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                </td>
                                <td>
                                    <?php if ($usuario['status']) { ?>
                                        <a class="btn default btn-xs red-stripe" href="javascript:;" onclick="modal_remover('<?php echo $this->url(
                                            'isconfiguracao-admin/default',
                                            array('controller' => 'usuarios', 'action' => 'ativarRemover', 'id' => $usuario['id'])
                                        ); ?>');">
                                            <i class="fa fa-remove"></i>
                                        </a>    
                                    <?php } else { ?>
                                        <a class="btn default btn-xs green-stripe" href="<?php echo $this->url('isconfiguracao-admin/default', array(
                                            'controller' => 'usuarios',
                                            'action' => 'ativarRemover',
                                            'id' => $usuario['id']
                                        )); ?>">
                                            <i class="fa fa-check"></i>
                                        </a>    
                                    <?php } ?>
                                </td>
                            <?php } ?>
                        </tr>
                    <?php }
                    if ($totalItens == 0) { ?>
                        <tr>
                            <td colspan="12">Nenhum registro localizado</td>
                        </tr>
                    <?php }
                    ?>
                </tbody>
            </table>
        </div>
        <?php if ($totalItens > 20) { ?>
            <div class="row">
                <div class="col-md-12 col-sm-12" >
                    <?php echo $this->paginationControl($dados, 'Sliding', 'partials/paginacao', array("filters" => $filtros)); ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>
<div id="modal_remover_item" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">ATENÇÃO</h4>
            </div>
            <div class="modal-body">
                <div class="scroller" style="height:50px" data-always-visible="1" data-rail-visible1="1">
                    <h4>Deseja realmente desativar este usuário?</h4>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-dismiss="modal" type="button"><i class="fa fa-remove"></i> Não</button>
                <a class="btn red-haze" id="modal_remover_botao" href="javascript:;"><i class="fa fa-check"></i> Sim</a>
            </div>
        </div>
    </div>
</div>
<div id="modal_acessos" class="modal fade" id="large" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">HISTÓRICO DOS 500 ÚLTIMOS ACESSOS</h4>
            </div>
            <div class="modal-body">
                <div id="conteudo" class="scroller" style="height:400px" data-always-visible="1" data-rail-visible1="1">

                </div>
            </div>
            <div class="modal-footer">
                <button class="btn default" data-dismiss="modal" type="button"><i class="fa fa-remove"></i> Fechar</button>
            </div>
        </div>
    </div>
</div>