<?php $totalItens = $dados->getTotalItemCount(); ?>
<h1 class="page-title">Cadastro de Cursos</h1>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="<?php echo $this->url('home'); ?>">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>Cursos</span>
        </li>
    </ul>
</div>
<div class="portlet light ">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-list font-yellow"></i>
            <span class="caption-subject font-yellow bold uppercase">Exibir/Buscar</span>
            <span class="caption-helper"><?php echo ISBase\Util\IdealizeUtil::itensLocalizados($totalItens, "curso"); ?></span>
        </div>
        <div class="actions">
            <a class="btn grey-mint pull-right" href="<?php echo $this->url('isconfiguracao-admin/default', array('controller' => 'cursos', 'action' => 'novo')); ?>">
                <i class="icon-plus"></i> Novo
            </a>
        </div>
    </div>
    <div class="portlet-body form">
        <?php echo $this->form()->openTag($form); ?>
        <div class="form-body">
            <?php echo $this->partial('partials/notificacoes'); ?>
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("status"));
                        echo $this->formElement($form->get("status"));
                        ?>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("unidade"));
                        echo $this->formElement($form->get("unidade"));
                        ?>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("tipo"));
                        echo $this->formElement($form->get("tipo"));
                        ?>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($form->get("nome"));
                        echo $this->formElement($form->get("nome"));
                        ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <button type="submit" class="btn grey-salt pull-right"><i class="fa fa-search"></i> Buscar</button>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
    <div class="portlet-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th class="text-center" width="400">Unidade</th>
                        <th class="text-center" width="200">Tipo</th>
                        <th class="text-center" width="10">Status</th>
                        <?php if ($acl['escrever']) { ?>
                            <th width="10"></th>
                            <th width="10"></th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($dados as $curso) { ?>
                        <tr>
                            <td>
                                <?php if ($acl['escrever']) { ?>
                                    <a href="<?php echo $this->url('isconfiguracao-admin/default', array('controller' => 'cursos', 'action' => 'editar', 'id' => $curso['id'])); ?>">
                                        <?php echo $curso['nome']; ?>
                                    </a>
                                <?php
                                    } else {
                                        echo $curso['nome'];
                                    }
                                    ?>
                            </td>
                            <td class="text-center"><?php echo $curso['unidade']; ?></td>
                            <td class="text-center"><?php echo \ISBase\Util\Arrays::cursosTipos($curso['tipo']); ?></td>
                            <td class="text-center"><?php echo $curso['status'] ? "<span class='label label-sm label-info'>Ativo</span>" : "<span class='label label-sm label-danger'>Inativo</span>"; ?></td>
                            <?php if ($acl['escrever']) { ?>
                                <td>
                                    <a class="btn default btn-xs yellow-stripe" href="<?php echo $this->url('isconfiguracao-admin/default', array('controller' => 'cursos', 'action' => 'editar', 'id' => $curso['id'])); ?>">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                </td>
                                <td>
                                    <?php if ($curso['status']) { ?>
                                        <a class="btn default btn-xs red-stripe" href="javascript:;" onclick="modal_remover('<?php echo $this->url('isconfiguracao-admin/default', array('controller' => 'cursos', 'action' => 'ativarRemover', 'id' => $curso['id'])); ?>');"> <i class="fa fa-remove"></i></a>
                                    <?php } else { ?>
                                        <a class="btn default btn-xs green-stripe" href="<?php echo $this->url('isconfiguracao-admin/default', array('controller' => 'cursos', 'action' => 'ativarRemover', 'id' => $curso['id'])); ?>"> <i class="fa fa-check"></i></a>
                                    <?php } ?>
                                </td>
                            <?php } ?>
                        </tr>
                    <?php }
                    if ($totalItens == 0) { ?>
                        <tr>
                            <td colspan="12">Nenhum registro localizado</td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php if ($totalItens > 20) { ?>
            <div class="row">
                <div class="col-md-12 col-sm-12">
                </div>
            </div>
        <?php } ?>
    </div>
</div>
<div id="modal_remover_item" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">ATENÇÃO</h4>
            </div>
            <div class="modal-body">
                <div class="scroller" style="height:50px" data-always-visible="1" data-rail-visible1="1">
                    <h4>Deseja realmente remover?</h4>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn default" data-dismiss="modal" type="button"><i class="fa fa-remove"></i> Não</button>
                <a class="btn red-haze" id="modal_remover_botao" href="javascript:;"><i class="fa fa-check"></i> Sim</a>
            </div>
        </div>
    </div>
</div>